version: '2'

services:
  mysql:
    image: mysql:5.6.45
    ports:
      - "3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=somepass
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    image: custom-php
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/app
